export const BUTTONS = [
  {
    key: ["`", "~", "ё", "Ё"],
    keyCode: 192,
    which: 192,
    code: "Backquote",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: true,
    repeat: false,
  },
  {
    key: ["1", "!", "1", "!"],
    keyCode: 49,
    which: 49,
    code: "Digit1",
    location: 0,
    description: "1 Key",
  },
  {
    key: ["2", "@", "2", '"'],
    keyCode: 50,
    which: 50,
    code: "Digit2",
    location: 0,
    description: "2 Key",
  },
  {
    key: ["3", "#", "3", "№"],
    keyCode: 51,
    which: 51,
    code: "Digit3",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: true,
    repeat: false,
  },
  {
    key: ["4", "$", "4", ";"],
    keyCode: 52,
    which: 52,
    code: "Digit4",
    location: 0,
    description: "4 Key",
  },
  {
    key: ["5", "%", "5", "%"],
    keyCode: 53,
    which: 53,
    code: "Digit5",
    location: 0,
    description: "5 Key",
  },
  {
    key: ["6", "^", "6", ":"],
    keyCode: 54,
    which: 54,
    code: "Digit6",
    location: 0,
    description: "6 Key",
  },
  {
    key: ["7", "&", "7", "?"],
    keyCode: 55,
    which: 55,
    code: "Digit7",
    location: 0,
    description: "7 Key",
  },
  {
    key: ["8", "*", "8", "*"],
    keyCode: 56,
    which: 56,
    code: "Digit8",
    location: 0,
    description: "8 Key",
  },
  {
    key: ["9", "(", "9", "("],
    keyCode: 57,
    which: 57,
    code: "Digit9",
    location: 0,
    description: "9 Key",
  },
  {
    key: ["0", ")", "0", ")"],
    keyCode: 48,
    which: 48,
    code: "Digit0",
    location: 0,
    description: "0",
  },
  {
    key: ["-", "_", "-", "_"],
    keyCode: 109,
    which: 109,
    code: "Minus",
    location: 3,
    description: "subtract",
  },
  {
    key: ["=", "+", "=", "+"],
    keyCode: 61,
    which: 61,
    code: "Equal",
    location: 0,
    description: "equals (firefox)",
  },
  {
    key: ["Backspace"],
    keyCode: 8,
    which: 8,
    code: "Backspace",
    location: 0,
    description: "editing",
    unicode: "⌫",
  },
  {
    key: ["Tab"],
    keyCode: 9,
    which: 9,
    code: "Tab",
    location: 0,
    description: "whitespace",
    unicode: "↹",
  },
  {
    key: ["q", "Q", "й", "Й"],
    keyCode: 81,
    which: 81,
    code: "KeyQ",
    location: 0,
    description: "q",
  },

  {
    key: ["w", "W", "ц", "Ц"],
    keyCode: 87,
    which: 87,
    code: "KeyW",
    location: 0,
    description: "w",
  },
  {
    key: ["e", "E", "у", "У"],
    keyCode: 69,
    which: 69,
    code: "KeyE",
    location: 0,
    description: "e",
  },
  {
    key: ["r", "R", "к", "К"],
    keyCode: 82,
    which: 82,
    code: "KeyR",
    location: 0,
    description: "r",
  },
  {
    key: ["t", "T", "е", "Е"],
    keyCode: 84,
    which: 84,
    code: "KeyT",
    location: 0,
    description: "t",
  },
  {
    key: ["y", "Y", "н", "Н"],
    keyCode: 89,
    which: 89,
    code: "KeyY",
    location: 0,
    description: "y",
  },
  {
    key: ["u", "U", "г", "Г"],
    keyCode: 85,
    which: 85,
    code: "KeyU",
    location: 0,
    description: "u",
  },
  {
    key: ["i", "I", "ш", "Ш"],
    keyCode: 73,
    which: 73,
    code: "KeyI",
    location: 0,
    description: "i",
  },
  {
    key: ["o", "O", "щ", "Щ"],
    keyCode: 79,
    which: 79,
    code: "KeyO",
    location: 0,
    description: "o",
  },
  {
    key: ["p", "P", "з", "З"],
    keyCode: 80,
    which: 80,
    code: "KeyP",
    location: 0,
    description: "p",
  },
  {
    key: ["[", "{", "х", "Х"],
    keyCode: 219,
    which: 219,
    code: "BracketLeft",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: ["]", "}", "ъ", "Ъ"],
    keyCode: 221,
    which: 221,
    code: "BracketRight",
    location: 0,
    description: "close bracket / å",
  },
  {
    key: ["\\", "|", "\\", "/"],
    keyCode: 220,
    which: 220,
    code: "Backslash",
    location: 0,
    description: "back slash",
  },
  {
    key: ["CapsLock"],
    keyCode: 20,
    which: 20,
    code: "CapsLock",
    location: 0,
    description: "modifier",
    unicode: "⇪",
  },
  {
    key: ["a", "A", "ф", "Ф"],
    keyCode: 65,
    which: 65,
    code: "KeyA",
    location: 0,
    description: "a",
  },
  {
    key: ["s", "S", "ы", "Ы"],
    keyCode: 83,
    which: 83,
    code: "KeyS",
    location: 0,
    description: "s",
  },
  {
    key: ["d", "D", "в", "В"],
    keyCode: 68,
    which: 68,
    code: "KeyD",
    location: 0,
    description: "d",
  },
  {
    key: ["f", "F", "а", "А"],
    keyCode: 70,
    which: 70,
    code: "KeyF",
    location: 0,
    description: "f",
  },
  {
    key: ["g", "G", "п", "П"],
    keyCode: 71,
    which: 71,
    code: "KeyG",
    location: 0,
    description: "g",
  },
  {
    key: ["h", "H", "р", "Р"],
    keyCode: 72,
    which: 72,
    code: "KeyH",
    location: 0,
    description: "h",
  },
  {
    key: ["j", "J", "о", "О"],
    keyCode: 74,
    which: 74,
    code: "KeyJ",
    location: 0,
    description: "j",
  },
  {
    key: ["k", "K", "л", "Л"],
    keyCode: 75,
    which: 75,
    code: "KeyK",
    location: 0,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: "k",
  },
  {
    key: ["l", "L", "д", "Д"],
    keyCode: 76,
    which: 76,
    code: "KeyL",
    location: 0,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: "l",
  },
  {
    key: [";", ":", "ж", "Ж"],
    keyCode: 186,
    which: 186,
    code: "Semicolon",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: ["'", '"', "э", "Э"],
    keyCode: 222,
    which: 222,
    code: "Quote",
    location: 0,
    description: "single quote / ø / ä",
  },
  {
    key: ["Enter"],
    keyCode: 13,
    which: 13,
    code: "Enter",
    location: 0,
    description: "whitespace",
    unicode: "↵",
  },
  {
    key: ["Shift"],
    keyCode: 16,
    which: 16,
    code: "ShiftLeft",
    location: 1,
    description: "modifier",
    unicode: "⇧",
  },
  {
    key: ["z", "Z", "я", "Я"],
    keyCode: 90,
    which: 90,
    code: "KeyZ",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
  },
  {
    key: ["x", "X", "ч", "Ч"],
    keyCode: 88,
    which: 88,
    code: "KeyX",
    location: 0,
    description: "x",
  },
  {
    key: ["c", "C", "с", "С"],
    keyCode: 67,
    which: 67,
    code: "KeyC",
    location: 0,
    description: "c",
  },
  {
    key: ["v", "V", "м", "М"],
    keyCode: 86,
    which: 86,
    code: "KeyV",
    location: 0,
    description: "v",
  },
  {
    key: ["b", "B", "и", "И"],
    keyCode: 66,
    which: 66,
    code: "KeyB",
    location: 0,
    description: "b",
  },
  {
    key: ["n", "N", "т", "Т"],
    keyCode: 78,
    which: 78,
    code: "KeyT",
    location: 0,
    description: "t",
  },
  {
    key: ["m", "M", "ь", "Ь"],
    keyCode: 77,
    which: 77,
    code: "KeyM",
    location: 0,
    description: "m",
  },
  {
    key: [",", "<", "б", "Б"],
    keyCode: 188,
    which: 188,
    code: "Comma",
    location: 3,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    description: "numpad period (firefox)",
  },
  {
    key: [".", ">", "ю", "Ю"],
    keyCode: 190,
    which: 190,
    code: "Period",
    location: 0,
    description: "period",
  },
  {
    key: ["/", "?", ".", ","],
    keyCode: 191,
    which: 191,
    code: "Slash",
    location: 0,
    description: "forward slash / ç",
  },
  {
    key: ["ArrowUp"],
    keyCode: 38,
    which: 38,
    code: "ArrowUp",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
    description: "navigation",
    unicode: "&#129093",
  },
  {
    key: ["Shift"],
    keyCode: 16,
    which: 16,
    code: "ShiftRight",
    location: 2,
    description: "modifier",
    unicode: "⇧",
  },
  {
    key: ["ctrl"],
    keyCode: 17,
    which: 17,
    code: "ControlLeft",
    location: 1,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    description: "modifier",
  },
  {
    key: ["Meta"],
    keyCode: 91,
    which: 91,
    code: "MetaLeft",
    location: 1,
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: "meta",
    unicode: "⊞",
  },
  {
    key: ["Alt"],
    keyCode: 18,
    which: 18,
    code: "AltLeft",
    location: 1,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: "modifier",
  },
  {
    key: [" "],
    keyCode: 32,
    which: 32,
    code: "Space",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
    description: "space",
  },
  {
    key: ["Alt"],
    keyCode: 18,
    which: 18,
    code: "AltRight",
    location: 2,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    description: "modifier",
  },
  {
    key: ["ctrl"],
    keyCode: 17,
    which: 17,
    code: "ControlRight",
    location: 2,
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    description: "modifier",
  },
  {
    key: ["ArrowLeft"],
    keyCode: 37,
    which: 37,
    code: "ArrowLeft",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
    description: "navigation",
    unicode: "&#129092",
  },
  {
    key: ["ArrowDown"],
    keyCode: 40,
    which: 40,
    code: "ArrowDown",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
    description: "navigation",
    unicode: "&#129095",
  },
  {
    key: ["ArrowRight"],
    keyCode: 39,
    which: 39,
    code: "ArrowRight",
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false,
    repeat: false,
    description: "navigation",
    unicode: "&#129094",
  },
];
